SESSION = 'n-estimators-5'

ITERS = 0

N_ESTIMATORS: int = 20

HIDDEN_DIMS: int = 128

BATCH_SIZE: int = 256
EPOCHS: int = 5
LR: float = 0.001
L2: float = 0.

LINES_DROPOUT: float = 0.
LINES_INPUT_DIMS: int = 100
LINES_IDX_I: int = 0
LINES_IDX_F: int = LINES_INPUT_DIMS
OFFSET = LINES_IDX_F

MACCS_ENABLE: bool = False
MACCS_DROPOUT: float = 0.
MACCS_INPUT_DIMS: int = 167
MACCS_IDX_I: int = OFFSET
MACCS_IDX_F: int = OFFSET + MACCS_INPUT_DIMS
OFFSET = MACCS_IDX_F if MACCS_ENABLE else OFFSET

TARGET_ENABLE: bool = False
TARGET_DROPOUT: float = 0.
TARGET_INPUT_DIMS: int = 100
TARGET_IDX_I = OFFSET
TARGET_IDX_F = OFFSET + TARGET_INPUT_DIMS
OFFSET = TARGET_IDX_F if TARGET_ENABLE else OFFSET

SMILES_KERNEL_DIMS: int = 32
SMILES_ENABLE: bool = True
SMILES_LEN: int = 400
SMILES_DIMS: int = 42
SMILES_INPUT_DIMS: int = int(SMILES_LEN*SMILES_DIMS)
SMILES_IDX_I: int = OFFSET
SMILES_IDX_F: int = OFFSET + SMILES_INPUT_DIMS

INPUT_DIMS = LINES_INPUT_DIMS
if MACCS_ENABLE:
    INPUT_DIMS += MACCS_INPUT_DIMS
if TARGET_ENABLE:
    INPUT_DIMS += TARGET_INPUT_DIMS
if SMILES_ENABLE:
    INPUT_DIMS += SMILES_INPUT_DIMS

SUMMARY: bool = True

CSV_PATH = 'data-hackathon'
TV_PATH = 'tv'
WEIGHTS_PATH = 'weights'
OBJ_PATH = 'obj'
